### ISSUE TITLE
propietario

### ISSUE THREAD

**Issue by albsierra** [Jose7420/CromaWave#1]
https://github.com/Jose7420/CromaWave/blob/648a843b0bd68be7b9660e3fee9261023c39e104/database/migrations/2024_04_21_154024_create_carritos.php#L18

El propietario no debe ser un `boolean` sino una relación con el usuario que crea el carrito. Además, si defines el `propietario` en la tabla `carritos`, ya no debes añadir otro `boolean` en la tabla `carritos_users`.

**Comment by Jose7420** [comment]
cambiado
